language: cpp

env:
  - LLVM_VERSION=3.5 GCC_VERSION=4.7
  - LLVM_VERSION=3.5 GCC_VERSION=4.8

before_install:
 - sudo add-apt-repository -y "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-${LLVM_VERSION} main"
 - sudo add-apt-repository -y 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise main'
 - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
 - sudo add-apt-repository -y 'deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main'
 - sudo apt-get update 
 - sudo apt-get install llvm-${LLVM_VERSION}-dev clang-${LLVM_VERSION} g++-${GCC_VERSION}
 - if [[ $CXX = "g++" ]]; then
     export CXX="g++-${GCC_VERSION}";
     export CC="gcc-${GCC_VERSION}"; 
   else 
     export CXX="clang++-${LLVM_VERSION}";
     export CC="clang-${LLVM_VERSION}";
   fi
 - export LLVM_CONFIG="llvm-config-${LLVM_VERSION}"
 - export BF_CLANG="clang-${LLVM_VERSION}"
 - export BF_CLANGXX="clang++-${LLVM_VERSION}"
 - export BF_GCC="gcc-{GCC_VERSION}"
 - export BF_GXX="g++{GCC_VERSION}"

script: 
  - autoreconf -i && ./configure && make distcheck

compiler:
  - clang
  - gcc
