language: cpp

env:
  - LLVM_VERSION=3.8 GCC_VERSION=4.8
  - LLVM_VERSION=3.8 GCC_VERSION=4.9

sudo: false

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - ccache
      - gcc-4.8
      - g++-4.8
      - gcc-4.9
      - g++-4.9
      - llvm-3.8-dev
      - clang-3.8

before_install:
 - if [[ $CXX = "g++" ]]; then
     export CXX="g++-${GCC_VERSION}";
     export CC="gcc-${GCC_VERSION}"; 
   else 
     export CXX="clang++-${LLVM_VERSION}";
     export CC="clang-${LLVM_VERSION}";
   fi
 - export LLVM_CONFIG="llvm-config-${LLVM_VERSION}"
 - export BF_CLANG="clang-${LLVM_VERSION}"
 - export BF_CLANGXX="clang++-${LLVM_VERSION}"
 - export BF_GCC="gcc-${GCC_VERSION}"
 - export BF_GXX="g++${GCC_VERSION}"

script: 
  - autoreconf -i && ./configure && make distcheck

compiler:
  - clang
  - gcc
